### ISSUE TITLE
broken link to git doc.

### ISSUE THREAD

**Issue by dlworldpeace** [ivegner/PokerAI#1]
Hi there, your link to cursedhydra.github.io shows 404 NotFound.

**Comment by ivegner** [comment]
Yep cheers thanks, removed. That was a link to an old demo site.

**Comment by ZachSchaffer** [comment]
Sorry about that, disappeared with my GitHub username change.

**Comment by dlworldpeace** [comment]
Thanks for the prompt reply! But can I get a link to the outline of your experience to learn from the whole process?
